<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{727f5f4a-fdfc-4f92-bb10-1d13c50fce2b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbCar 	: FB_Beckhoff_EV;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbCar();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>