<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_Beckhoff_Energy_Source" Id="{4c0fb772-c3eb-4865-a964-57fe6b300b80}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Beckhoff_Energy_Source
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Methods" Id="{e75f9da0-5c45-45a1-8b39-927292ffd781}" />
    <Folder Name="Properties" Id="{4c8e350b-674a-4174-ac22-237a5841c42f}" />
    <LineIds Name="FB_Beckhoff_Energy_Source">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>