<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_Beckhoff_Auxilary" Id="{eb9110a2-3fe1-44c4-92a8-343f88ed7467}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Beckhoff_Auxilary
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Methods" Id="{2ca2faa1-95cb-45f3-ab61-0b9a77bae127}" />
    <Folder Name="Properties" Id="{f0043917-6eb3-4dc8-8615-ec2ad0647ca9}" />
    <LineIds Name="FB_Beckhoff_Auxilary">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>