<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FB_Hash_Map" Id="{0d2d9a59-245c-442d-bc89-295cb0cac54a}" SpecialFunc="None">
    <Declaration><![CDATA[// A collection of key value pairs items.
{attribute 'enable_dynamic_creation'}
{attribute 'no_assign'}
{attribute 'no_explicit_call' := 'direct call for this function block is not allowed'}
FUNCTION_BLOCK FB_Hash_Map EXTENDS FB_Collection
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Hash_Map">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>