<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_Matching_Generics" Id="{ae83e078-55c1-0df1-27ad-9d245eac105d}" SpecialFunc="None">
    <Declaration><![CDATA[// Checks if 2 generics can be compared to see if they match (same size, same class). Match = TRUE, Not Matching = FALSE.
// The exception is strings. If 2 generics are strings they're considered to be matching regardless of size;
FUNCTION F_Matching_Generics : BOOL
VAR_INPUT
	A, B : T_Generic;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_Matching_Generics := 
	(A.diSize = B.diSize AND_THEN A.TypeClass = B.TypeClass)
	OR_ELSE
	(A.TypeClass = __SYSTEM.TYPE_CLASS.TYPE_STRING AND_THEN B.TypeClass = __SYSTEM.TYPE_CLASS.TYPE_STRING)
	OR_ELSE
	(A.TypeClass = __SYSTEM.TYPE_CLASS.TYPE_WSTRING AND_THEN B.TypeClass = __SYSTEM.TYPE_CLASS.TYPE_WSTRING);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>