<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{17732e83-93d3-4e32-896f-74d26e2dd9ab}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbArray_List_Test : FB_Array_List_Test;
	fbList_Test : FB_List_Test;
	// Add test for Array
	// Add test for Immutable list and array
	// Add test for Set
	// Add test for Immutable Set
	// Add test for Tree Map
	// Add test for Hash Map
	// Add test for Immutable Map
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="142" Count="0" />
      <LineId Id="155" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>