<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Hash_Map" Id="{2f3dc51d-9a32-0b7c-3648-fa7ef11990ef}" SpecialFunc="None">
    <Declaration><![CDATA[// A collection of key value pairs items.
{attribute 'enable_dynamic_creation'}
{attribute 'no_assign'}
{attribute 'no_explicit_call' := 'direct call for this function block is not allowed'}
FUNCTION_BLOCK FB_Hash_Map EXTENDS FB_Collection
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>