<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FB_Hash_Set" Id="{727077f2-d867-0e9a-31ad-aa798d2a6585}" SpecialFunc="None">
    <Declaration><![CDATA[// A collection that contains no duplicate items.
{attribute 'enable_dynamic_creation'}
{attribute 'no_assign'}
{attribute 'no_explicit_call' := 'direct call for this function block is not allowed'}
FUNCTION_BLOCK FB_Hash_Set EXTENDS FB_Collection
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Hash_Set">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>